language: java
dist: trusty
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk8
# whitelist
branches:
  only:
    - solutions
os:
- linux
cache:
directories:
- $HOME/.gradle
script:
  - ./gradlew check
